### ISSUE TITLE
NS cases-by-zone no longer updating

### ISSUE THREAD

**Issue by chenein** [ccodwg/Covid19CanadaArchive#161]
Data is saved every night, but the last record in the file is consistently April 18, 2021.

**Comment by jeanpaulrsoucy** [comment]
Thanks, they switch out the data files sometimes and I usually don't catch it until someone complains (or I need to use it personally). Will give it a look today!

**Comment by jeanpaulrsoucy** [comment]
Review of NS dashboard files still active:

- [x] cases-by-zone (Zones_V4_PROD)
- [x] zone-summary (BND_NSH_MZones_V4_Join_PROD)
- [x] zone-summary-cases (Zones_MaxDate_V4_PROD)
- [x] chn-summary-cases (BND_NS_CommunityHealthNetworks_Join_PROD)
- [x] serious-outcomes (Serious_Outcomes_V4_PROD)
- [x] lab-testing (Lab_Testing_V4_PROD)
- [x] lab-testing-hos-icu-summary (Lab_Testing_MaxDate_V4_PROD)
- [x] demographics-summary (Demographics_V4_PROD)
- [x] health-boundaries (Health_Boundaries_PROD)
- [ ] immunizations-2 (Immunizations_3_PROD)

New files:
- Immunizations_V4_PROD

Need to update immunization file for NS.

According to the file index, cases-by-zone (Zones_V4_PROD) has not had a file update since April 19, 2021. However, it is still being called by the NS dashboard (perhaps old code that has not been removed yet).

**Comment by jeanpaulrsoucy** [comment]
As to your original problem, @chenein, it appears the relevant information is still actively updated in zones-summary-cases, as well as other files.

**Comment by chenein** [comment]
Thanks @jeanpaulrsoucy, this is a great dataset. I'll work from the summary files.

**Comment by jeanpaulrsoucy** [comment]
@chenein you've given me the idea for a script to automatically identify stale datasets (and thus prompt me to check for most recent versions of the datasets) - tracking it here: #163. Thanks again!
