### ISSUE TITLE
Add INSPQ variants screening CSVs

### ISSUE THREAD

**Issue by mschoettle** [ccodwg/Covid19CanadaArchive#180]
INSPQ has some new datasets regarding screening for variants. They are shown here: https://www.inspq.qc.ca/covid-19/donnees/variants

* https://www.inspq.qc.ca/sites/default/files/covid/donnees/variants-criblage.csv
* https://www.inspq.qc.ca/sites/default/files/covid/donnees/variants-criblage-sem.csv

**Comment by jeanpaulrsoucy** [comment]
Thanks @mschoettle. Any idea what the difference between the two files is? I've given the one with more columns the relatively uninformed name of variant screening (expanded). While this dataset (variants-criblage-sem) has more columns than the first one, it doesn't appear to contain all of the columns the first one does (e.g., I don't see "b117_pond1_cum_n" in the second file).

I only had time to give the files a quick glance since I wanted to add the files before the update ran at 22:00 tonight and INSPQ does use a very brief (and thus sometimes cryptic) naming scheme...

**Comment by mschoettle** [comment]
Good question. When I initially sglanced over the files I couldn't immediately figure it out.

The two files only have 4 columns in common: `['SemCDC', 'Regroupement', 'Croisement', 'RSS_NOM']`

In general, INSPQ uses `_quo_` for daily numbers, `_cum_` for total numbers, `_n` for the number, `_t` for the rate (always per 100k I believe).

So to me it looks like `variants-criblage` contains the total numbers and `variants-criblage-sem` the weekly numbers (the columns all contain `_heb_`).

**Comment by jeanpaulrsoucy** [comment]
I think you've got it. SemCDC is the "epidemiological week". I'll rename accordingly.
